### ISSUE TITLE
Remove global registry

### ISSUE THREAD

**Issue by matt-gadd** [dojo/widget-core#582] opened 2017-06-19 12:06 UTC
**Enhancement** 
As part of our work on SSR, its proven problematic to have a global registry singleton. We would like to keep the idea of a top level registry for ease of use, but not via a singleton. 

In order to accomplish this we're going to allow a top level registry to be passed as a property in the projector (or if one not passed, the projector to create), and this will automatically be carried down the tree to all widgets. This will be then used in the `RegistryHandler` mechanism as it is today.

**Comment by kitsonk** [comment] 2017-06-19 12:20
That sounds reasonable and logical to me. 👍

**Comment by kitsonk** [comment] 2017-07-28 07:04
Duplicate of #457

**Comment by agubler** [comment] 2017-10-06 08:45
Addressed initially in #636

**Closed by agubler** 2017-10-06 08:45 UTC
Labels: beta3, breaking-change, enhancement
