### ISSUE TITLE
Container/Injector Documentation?

### ISSUE THREAD

**Issue by mwistrand** [dojo/widget-core#697] opened 2017-09-27 15:32 UTC
**Enhancement**

I've noticed there is no reference to either the `Container` or the `Injector` in the project README. Given that they are both rather important, documentation for them should be included in the README.

**Comment by agubler** [comment] 2017-10-02 11:54
Duplicate of https://github.com/dojo/widget-core/issues/671

**Closed by agubler** 2017-10-02 11:54 UTC
Labels: beta4, documentation
