### ISSUE TITLE
afterRender fires to early

### ISSUE THREAD

**Issue by sebilasse** [dojo/widget-core#627] opened 2017-07-31 17:47 UTC
my root node seems NOT to be rendered in `afterRender` 

`console.log( this.meta(Dimensions).has('root'), this.meta(Dimensions).get('root') );`
returns
`false` and `0` everywhere ...

**Comment by agubler** [comment] 2017-07-31 18:08
Hi, @sebilasse is there any chance you could post a complete minimal example of the issue?

**Comment by sebilasse** [comment] 2017-08-01 09:05
Hi @agubler -
put all the semantic widgets in a repo to demo it (preview, WIP) :
https://github.com/sebilasse/Semantic-UI-Dojo

Please forgive me that the code is badly documented and without tests for now.
Also there is only one theme included but it should work with any semantic ui theme.

I have simply put the above code in the Checkbox widget and put the Checkbox in App below the Accordion. 

So simply `npm i` + `dojo build -w` and look at console ...

The only problem is that there might be two errors (because as an early bird doing things for >6months I am using TS 2.5 already), described here https://github.com/dojo/cli-build-webpack/issues/187

BTW : I would be thankful for _any_ comment about mistakes made or possible improvements of the code ...

**Comment by kitsonk** [comment] 2017-08-01 11:53
@sebilasse I am afraid recreating your development environment is beyond the scope of what we can be reasonably expected to do.  A minimal example would be something that either can be expressed in a reasonable code snippet or something that can be linked to in a CodePen or a JSFiddle.

When testing code under NodeJS with jsdom, it is important to realise that the meta functionality is often a multi-pass situation where until the DOM is actually projected, the meta provider doesn't actually have something it can operate on, so it may return an "empty" value.  So usually it requires at least one full render of the DOM, which requires the `requestAnimationFrame` to be resolved.  If you are checking values in a synchronous fashion, what you are stating is likely to occur, but if the values are checked asynchronously, they will likely be what you would expect them to be.

As you can see from the [tests](https://github.com/dojo/widget-core/blob/0fe2cf20fc923cb9c82127578ee210a3c0442c96/tests/unit/meta/Dimensions.ts#L51) we are stubbing and manually resolving the rAF before inspecting the results.

**Comment by sebilasse** [comment] 2017-08-01 12:43
Ok. I can also put the above in a codepen (but isn't it the same ?) - is dojo2 CDN hosted anywhere (otherwise I have to put it on a server first).

**Comment by agubler** [comment] 2017-08-01 13:29
@sebilasse Ideally we would have a minimal example that reproduces your issue, that can be in a codepen or an example repository.

This will help us diagnose underlaying issues or help you figure out if there is something that was missed in your code first time.

I often use the dojo cli to create an example project and then write my isolated repro. In this instance I have created an example of the sort of thing that we would be looking for along with the issue, https://github.com/agubler/dojo-2-dimensions-issue. As you can see this is clear, easy to understand and reproduce the issue you were experiencing.

**Comment by agubler** [comment] 2017-08-01 13:56
I would also ask why you are getting dimensions in the `afterRender` and not in the actual render itself?

**Comment by sebilasse** [comment] 2017-08-01 14:43
@agubler Good question. Forgot to mention ...
Because when I used it in `render` I got the following error
```
Error: Functions may not be updated on subsequent renders (property: onChange). Hint: declare event handler functions outside the render() function.
```
And then I looked at each piece in my widgets but there seemed to be no event handler which is inside the render(). They should all be own member functions of the widget. But I will check again now !

**Comment by agubler** [comment] 2017-08-01 14:51
how did you use it in the `render()`? 

```ts
render() {
     const { size } = this.meta(Dimensions).get('root');
     // ... do other stuff with the size information
}
```

**Comment by sebilasse** [comment] 2017-08-01 15:01
well, basically yes
```
render() {
    const dimensions = this.meta(Dimensions).get('root');
    console.log( 'dimensions', dimensions );
    return v(ElementType, props, children);
}
```

**Comment by sebilasse** [comment] 2017-08-01 15:02
Yes, it would be fine if the error tells me which "onChange" is meant
<img width="760" alt="bildschirmfoto 2017-08-01 um 17 01 55" src="https://user-images.githubusercontent.com/750300/28831870-3ade8d50-76db-11e7-9a86-eb11c5e55abe.png">

**Comment by agubler** [comment] 2017-08-01 15:05
So you seem to be creating a new function for your handlers in `App.ts`

```ts
e(msg: string) { return ((e: any) => { console.log(msg, e) }); }
```

And as you are spreading these directly onto the props in `v`, then it will be a new function every render.

**Comment by sebilasse** [comment] 2017-08-01 15:09
Yes, this was just for debugging events because in all function only the message would change (just wanted to log the event). But it is "outside render()" - so isn't that ok ?

**Comment by agubler** [comment] 2017-08-01 15:13
It needs to be the "same" reference, so generally if you define a function outside of the `render` it will be the same reference... However in your code it's actually still technically being created from within the render cycle (by calling `this.e(...)`) and then used directly on a `v()` node which still means every render it will be a new reference (a new function every render).

**Comment by sebilasse** [comment] 2017-08-01 15:25
ah - I see ... Then I'll correct this and play further with the unfinished draggable. 
Thankyou again !

But I should be able to use `this.meta` also in events as `_onDragStart`, right?

And one more question: When I want only one property from a node (e.g. ownerDocument which could be iframed) - would you write it's own meta class or somehow directly get the node ?

**Comment by agubler** [comment] 2017-08-02 06:50
@sebilasse I am going to close this issue for now, please re-open if you experience further issues.

To conclude, meta should not be used in an `afterRender` as it will work as intended. Using meta in an event handler is possible but will only return the expected dimensions if you have done a get within the previous render.

**Closed by agubler** 2017-08-02 06:50 UTC
Labels: needs info
