### ISSUE TITLE
Handle uncontrolled form components.

### ISSUE THREAD

**Issue by dylans** [dojo/widget-core#385] opened 2017-03-06 14:20 UTC
From https://github.com/dojo/widgets/issues/38#issuecomment-283687745

> For beta we will have a form widget that works with controlled components only.
> We will document this restriction.
> At a later date, we will raise an issue on widget-core for a way to handle uncontrolled components also.

This ticket is to determine a way to handle uncontrolled components.

**Comment by bitpshr** [comment] 2017-03-06 14:25
For some added context, uncontrolled components can technically already be used. A parent component can add supported handlers, e.g. `onInput`, to a child component, and cache child values as they update. This is exactly what is done for controlled components, the only difference being that in a controlled flow, the cached value is passed back to the child, thus "completing the circle".

I still think this ticket can serve as a place to discuss something like React's `ref` to make this easier, though.

**Comment by kitsonk** [comment] 2017-07-28 09:56
Duplicate of dojo/widgets#22

**Closed by kitsonk** 2017-07-28 09:56 UTC
Labels: discussion, enhancement
